apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.{{ .Values.domainSuffix }}`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
  tls:
    secretName: argo-ui-tls
