apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-ui
  namespace: {{ .Release.Namespace }}
spec:
  secretName: longhorn-ui-tls
  commonName: "longhorn.{{ .Values.domainSuffix }}"
  dnsNames:
    - "longhorn.{{ .Values.domainSuffix }}"
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
