apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.21.0
      helm:
        values: |
          crds:
            enabled: true
    - repoURL: https://github.com/hadcrab/k8s-homelab-manifests.git
      targetRevision: HEAD
      path: platform/certmgr
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
