apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.12.0
      helm:
        values: |
          persistence:
            defaultClassReplicaCount: 2
          defaultSettings:
            defaultReplicaCount: 2
            replicaAutoBalance: least-effort
            storageMinimalAvailablePercentage: 5
            storageReservedPercentageForDefaultDisk: 5
    - repoURL: https://github.com/hadcrab/k8s-homelab-manifests.git
      targetRevision: HEAD
      path: platform/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
