domainSuffix: "kube"

alertmanager:
  enabled: false

grafana:
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi
  adminPassword: admin

kubeStateMetrics:
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi

prometheus:
  prometheusSpec:
    scrapeInterval: 60s
    evaluationInterval: 60s
    retention: 2d
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
  ingress:
    enabled: false

nodeExporter:
  resources:
    limits:
      memory: 64Mi
    requests:
      memory: 32Mi
