apiVersion: v2
name: loki
description: Loki for logs
type: application
version: 0.1.0
appVersion: "7.1.0"
dependencies:
  - name: loki
    version: 7.1.0
    repository: https://grafana.github.io/helm-charts