apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - git:
              repoURL: https://github.com/hadcrab/k8s-homelab-manifests.git
              revision: HEAD
              directories:
                - path: charts/*
          - list:
              elements:
                - name: metallb
                  namespace: metallb-system
                  skipCrds: "false"
                - name: traefik
                  namespace: traefik-system
                  skipCrds: "false"
                - name: certmgr
                  namespace: cert-manager
                  skipCrds: "false"
                - name: longhorn
                  namespace: longhorn
                  skipCrds: "false"
                - name: monitoring-crds
                  namespace: monitoring
                  skipCrds: "false"
                - name: monitoring
                  namespace: monitoring
                  skipCrds: "true"
                - name: argocd
                  namespace: argocd
                  skipCrds: "false"
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/hadcrab/k8s-homelab-manifests.git
        targetRevision: HEAD
        path: 'charts/{{name}}'
        helm:
          skipCrds: '{{skipCrds}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
