apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - path.basename
        generators:
          - git:
              repoURL: https://github.com/hadcrab/k8s-homelab-manifests.git
              revision: HEAD
              directories:
                - path: charts/*
          - list:
              elements:
                - path.basename: metallb
                  namespace: metallb-system
                - path.basename: traefik
                  namespace: traefik-system
                - path.basename: certmgr
                  namespace: cert-manager
                - path.basename: longhorn
                  namespace: longhorn
                - path.basename: monitoring-crds
                  namespace: monitoring
                - path.basename: monitoring
                  namespace: monitoring
                - path.basename: argocd
                  namespace: argocd
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/hadcrab/k8s-homelab-manifests.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
