apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-grafana
  namespace: {{ .Release.Namespace }}
spec:
  secretName: monitoring-grafana-tls
  commonName: "grafana.{{ .Values.domainSuffix }}"
  dnsNames:
    - "grafana.{{ .Values.domainSuffix }}"
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
